#!/usr/bin/env bash
# Script that install HA Proxy
# Update the package list and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy to send traffic to web-01 and web-02 using a roundrobin algorithm
sudo bash -c 'cat << EOF > /etc/haproxy/haproxy.cfg
frontend http-in
    bind *:80
    default_backend servers
backend servers
    balance roundrobin
    server 175278-web-01 54.210.59.183:80 check
    server 175278-web-02 100.26.246.40:80 check
EOF'

# Make sure that HAProxy can be managed via an init script
sudo systemctl enable haproxy

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy
